---
title: "T1 - Generar gràfiques diapositives"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source('utils.R')
carrega_llibreries()
```


## Coronavirus

Carreguem les dades (font: European Centre for Disease Prevention and Control https://www.ecdc.europa.eu).

```{r}
dades = read.csv(url('https://raw.githubusercontent.com/PBibiloni/Mates1/master/dades/coronavirus_9sept.csv'))
dades_mundials = dades[, c('day', 'month', 'year', 'cases')]
dades_mundials = aggregate(cases ~ year + month + day, data=dades_mundials, FUN=sum)
dades_mundials = dades_mundials[order(dades_mundials$year, dades_mundials$month, dades_mundials$day), ]
dades_mundials[, 'cum. cases'] = cumsum(dades_mundials[, 'cases'])
dades_mundials['data'] = make_date(dades_mundials$year, dades_mundials$month, dades_mundials$day)
```


```{r}
ggplot(dades_mundials, aes(x=data)) +
        geom_line(aes(y=cases)) +
        labs(title="Sèrie mundial coronavirus", y="Casos nous") +
        theme(axis.title.x=element_blank())
guarda_ggplot(tema=1, nom='Coronavirus_serie_mundial_lineal_1.png')

# Gràfica mostrant només els primers 90 dies.
ggplot(dades_mundials[1:90, ], aes(x=data)) +
        geom_line(aes(y=cases)) +
        labs(title="Sèrie mundial coronavirus", y="Casos nous") +
        theme(axis.title.x=element_blank())
guarda_ggplot(tema=1, nom='Coronavirus_serie_mundial_lineal_2.png')

# Gràfica mostrant només els primers 60 dies.
ggplot(dades_mundials[1:60, ], aes(x=data)) +
        geom_line(aes(y=cases)) +
        labs(title="Sèrie mundial coronavirus", y="Casos nous") +
        theme(axis.title.x=element_blank())
guarda_ggplot(tema=1, nom='Coronavirus_serie_mundial_lineal_3.png')

# Gràfica mostrant només els primers 30 dies.
ggplot(dades_mundials[1:30, ], aes(x=data)) +
        geom_line(aes(y=cases)) +
        labs(title="Sèrie mundial coronavirus", y="Casos nous") +
        theme(axis.title.x=element_blank())
guarda_ggplot(tema=1, nom='Coronavirus_serie_mundial_lineal_4.png')

# Gràfica semi-log eliminant els valors que són igual a zero.
ggplot(dades_mundials[-1:-17, ], aes(x=data)) +
        scale_y_continuous(trans='log10') +
        geom_line(aes(y=cases)) + 
        labs(title="Sèrie mundial coronavirus (semilog)", y="Casos nous") +
        theme(axis.title.x=element_blank())
guarda_ggplot(tema=1, nom='Coronavirus_serie_mundial_semilog.png')
```


Exportem també les dades numèriques:

```{r}
fileres_quinzenes = dades_mundials[, 'day'] == 1 | dades_mundials[, 'day'] == 15
dades_mundials_quinzenes = dades_mundials[fileres_quinzenes, c('data', 'cases', 'cum. cases')]
dades_mundials_quinzenes['log10(cases)'] = log10(dades_mundials_quinzenes[, 'cases'])
dades_mundials_quinzenes['log10(cum. cases)'] = log10(dades_mundials_quinzenes[, 'cum. cases'])
print(dades_mundials_quinzenes[ , c('data', 'cases', 'log10(cases)')])
xtable(dades_mundials_quinzenes[ , c('data', 'cases', 'log10(cases)')])
```

 I les dades amb casos acumulats:
 
```{r}
print(dades_mundials_quinzenes[ , c('data', 'cases', 'log10(cases)', 'cum. cases', 'log10(cum. cases)')])
xtable(dades_mundials_quinzenes[ , c('data', 'cases', 'log10(cases)', 'cum. cases', 'log10(cum. cases)')])
```











# Definició d'exponencial


```{r}
eix_x = -4:4
base_exponencial = 2
funcio_exponencial = function(x) base_exponencial^x
funcio_tex = unname(TeX(paste(base_exponencial, "^x")))
x_lims = range(eix_x)

df = data.frame(x=eix_x,
                y=funcio_exponencial(eix_x))

# Només punts >= 0
ggplot(df[df$x >= 0, ], aes(x, y)) +
        geom_point() +
        scale_x_continuous(breaks=seq(x_lims[1], x_lims[2], 2), limits=x_lims) +
        scale_y_continuous(limits=c(-1, max(df$y)+1)) +
        labs(title=unname(TeX(paste("Funció exponencial $y(x) = ", base_exponencial, "^x$"))), 
             x="Eix x", y="Eix y")
guarda_ggplot(tema=1, nom='DefExponencial_1.png')

# Només punts
ggplot(df, aes(x, y)) +
        geom_point() +
        scale_x_continuous(breaks=seq(x_lims[1], x_lims[2], 2), limits=x_lims) +
        scale_y_continuous(limits=c(-1, max(df$y)+1)) +
        labs(title=unname(TeX(paste("Funció exponencial $y(x) = ", base_exponencial, "^x$"))), 
             x="Eix x", y="Eix y")
guarda_ggplot(tema=1, nom='DefExponencial_2.png')

# Punts i recta
ggplot(df, aes(x, y)) +
        geom_point() +
        scale_x_continuous(breaks=seq(x_lims[1], x_lims[2], 2), limits=x_lims) +
        scale_y_continuous(limits=c(-1, max(df$y)+1)) +
        labs(title=unname(TeX(paste("Funció exponencial $y(x) = ", base_exponencial, "^x$"))), 
             x="Eix x", y="Eix y") +
        stat_function(fun = funcio_exponencial)
guarda_ggplot(tema=1, nom='DefExponencial_3.png')
```
