---
title: "T2 - Material per a les diapositives"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source('utils.R')
carrega_llibreries()
```



## Dependències lineals i exponencials

```{r}
ggplot(data.frame(x=0), aes(x)) +
    scale_y_continuous(limits=c(-1, 10)) +
    scale_x_continuous(limits=c(-1, 10)) +
    stat_function(fun = function(x) 0.5*x+2, geom="line") +
    annotate(geom="text", x=2, y=1, label=unname(TeX("$0.5x+2$")), size=12, color="#CC0000") + 
    theme(axis.title.x=element_blank(), axis.title.y=element_blank())
guarda_ggplot(tema=2, nom='DependenciaLineal_GraficaLineal.png')
```


```{r}
ggplot(data.frame(x=0), aes(x)) +
    scale_y_continuous(limits=c(-1, 1e5)) +
    scale_x_continuous(limits=c(-1, 10)) +
    stat_function(fun = function(x) 0.1 * 4^x, geom="line") +
    annotate(geom="text", x=3, y=1e4, label=unname(TeX("$0.1 \\cdot 4^x$")), size=12, color="#CC0000") + 
    theme(axis.title.x=element_blank(), axis.title.y=element_blank())
guarda_ggplot(tema=2, nom='DependenciaExponencial_GraficaLineal.png')
```




## Def gràfica semi-log

```{r}
dades = read.csv(url('https://raw.githubusercontent.com/PBibiloni/Mates1/master/dades/coronavirus_9sept.csv'))
dades_mundials = dades[, c('day', 'month', 'year', 'cases')]
dades_mundials = aggregate(cases ~ year + month + day, data=dades_mundials, FUN=sum)
dades_mundials = dades_mundials[order(dades_mundials$year, dades_mundials$month, dades_mundials$day), ]
dades_mundials[, 'cum. cases'] = cumsum(dades_mundials[, 'cases'])
dades_mundials['data'] = make_date(dades_mundials$year, dades_mundials$month, dades_mundials$day)

ggplot(dades_mundials[-1:-17, ], aes(x=data)) +
    scale_y_continuous(trans='log10', labels=function(n) unname(TeX(paste("$10^", log10(n), "$")))) +
    geom_line(aes(y=cases)) + 
    labs(y=unname(TeX("$y = $Casos nous"))) +
    theme(axis.title.x=element_blank())
guarda_ggplot(tema=2, nom='Coronavirus_semilog_v1.png')

ggplot(dades_mundials[-1:-17, ], aes(x=data)) +
    scale_y_continuous(trans='log10', labels=function(n) sprintf('%d', log10(n))) +
    geom_line(aes(y=cases)) + 
    labs(y=unname(TeX("$Y = \\log_{10}$(Casos nous)"))) +
    theme(axis.title.x=element_blank())
guarda_ggplot(tema=2, nom='Coronavirus_semilog_v2.png')
```


## Exemple dibuixar gràfica semi-log

Gràfiques per mostrar fer-ho a mà:

```{r}
f = function(x) 2 * 4.5^x
valors_x = seq(0, 10, 2)
df = data.frame(x=valors_x, y=f(valors_x), Y=log10(f(valors_x)))

# Export datapoints as Latex table
xtable(df)

# Print datapoints Y(x)
ggplot(df, aes(x, y)) +
    scale_y_continuous(trans='log10', labels=function(n) sprintf('%d', log10(n))) +
    labs(y=unname(TeX("$Y = \\log(y)$"))) +
    geom_point()

# Add line
ggplot(df, aes(x, y)) +
    scale_y_continuous(trans='log10', labels=function(n) sprintf('%d', log10(n))) +
    labs(y=unname(TeX("$Y = \\log(y)$"))) +
    geom_point() + geom_line()

# Replace ticks
ggplot(df, aes(x, y)) +
    scale_y_continuous(trans='log10', labels=function(n) unname(TeX(paste("$10^", log10(n), "$")))) +
    labs(y=unname(TeX("$y$"))) +
    geom_point() + geom_line()
```



